import AlertNotFound from './AlertNotFound';
import Benefits from './Benefits';
import CrossRoads from './CrossRoads';
import Dummy from './Dummy';
import Footer from './Footer';
import Header from './Header';
import Hero from './Hero';
import Highlight from './Highlight';
import InfoBoxes from './InfoBoxes';
import Map from './Map';
import Reviews from './Reviews';
import TextBlock from './TextBlock';
import DoctorList from './DoctorList';
import PolyclinicsList from './PolyclinicsList';
import ExpertiseList from './ExpertiseList';
export { AlertNotFound, Benefits, CrossRoads, Dummy, Footer, Header, Hero, Highlight, InfoBoxes, Map, Reviews, TextBlock, DoctorList, PolyclinicsList, ExpertiseList, };
